# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~# CatUserBot #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Copyright (C) 2020-2023 by TgCatUB@Github.

# This file is part of: https://github.com/TgCatUB/catuserbot
# and is released under the "GNU v3.0 License Agreement".

# Please see: https://github.com/TgCatUB/catuserbot/blob/master/LICENSE
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

version: '3.3'

services:
 app:
    container_name: cat
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m userbot
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/catuserbot
    depends_on:
      - db

 db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catuserbot
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  botdata:
    driver: local

