##############################
# Please edit this line to "not_sample_anymore" to make the bot run
is_example_config_or_not: "Ahhhhhhhhhhh i am not blind so i'll follow what the line above me asked"
##############################
bot_token: "Your bot token"
api_key: ''
api_hash: ''
owner_id: 123456
owner_username: "OWNER USERNAME"
message_dump: "CHAT ID"
gban_dump: "CHAT ID"
load: []
no_load: []
strict_antispam: False
workers: 4
deepfry_token: None
del_cmds: False
sw_api: ''

# Database
database_url: "postgres://username:password@host:5432/database_name"

# Permission
sudo_users: []
support_users: []
whitelist_users: []
